config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :companies, controllers: {
    sessions: 'companies/sessions',
    passwords: 'companies/passwords',
    registrations: 'companies/registrations'

  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  # トップページ
  root 'pages#home', as: 'root'
  get '/search', to: 'pages#search', as: 'pages_search'
  get '/detail/:id', to: 'pages#detail'
  post 'pages/create/:id', to: 'pages#create'
  # ユーザーページ
  get '/users/profile', to: 'users#profile', as: 'profile'
  get '/users/confirmation', to: 'users#confirmation'
  # ユーザーのプロフィールページの編集
  patch '/users/profile/edit', to: 'users#update'
  # 企業ページ
  get 'companies/confirmation', to: 'companies#confirmation'
  get '/companies/review', to: 'companies#review'
  get '/companies/show', to: 'companies#show', as: 'companies_show'
  # 募集ページ
  get '/companies/offer', to: 'companies#offer'
  post '/companies/create', to: 'companies#create'
  delete '/companies/offer/:id', to: 'companies#destroy'
  get '/companies/offer/:id/edit', to: 'companies#edit'
  patch '/companies/offer/:id', to: 'companies#update'
end

app/views/pages/detail.html.erb
<div class="container col-lg-9">
        <div class="card detail-image-card ">
          <img src="<%= @offer.images.to_s%>" class="detail-image">
        </div>
        <h4 class="detail-title"><%=@offer.title%></h4>
        <span class="badge badge-success"><%=@offer.category.name%></span>
        <%@offer.offer_walfares.each do |offer_walfare|%>
        <span class="badge badge-success">
            <%=offer_walfare.walfare.name%>
        </span>
        <%end%>
        <table class="table table-bordered">
          <tbody>
            <tr>
              <th class="text-nowrap" style="width: 120px">日時</th>
              <td><%=@offer.date.strftime("%Y年%m月%d日")%><br><%= @offer.start_time%>〜<%= @offer.end_time%></td>
            </tr>
            <tr>
              <th>仕事内容</th>
              <td><%= simple_format(@offer.contents) %></td>
            </tr>
            <tr>
              <th>注意事項</th>
              <td><%=simple_format(@offer.cautions)%></td>
            </tr>
            <tr>
              <th>持ち物</th>
              <td><%=@offer.belongings%></td>
            </tr>
            <tr>
              <th>働くための条件</th>
              <td><%=simple_format(@offer.conditions)%></td>
            </tr>
            <tr>
              <th>勤務先住所</th>
              <td><%=@offer.address%></td>
            </tr>
            <tr>
              <th>報酬</th>
              <td>¥<%=@offer.payment.to_s(:delimited)%></td>
            </tr>
        </table>
        <p>※連絡先は応募終了後に確認できます</p>
        <div class="applicaton-button text-right">
          <%if user_signed_in?%>
            <%=form_with scope: :applicants, url: "/pages/create/"+@offer.id.to_s, local: true do |f|%>
              <%= f.submit "応募する", class: "btn btn-primary submit-button" %>
            <% end %>
          <%else%>
            <a href="/users/sign_in", class="btn btn-primary submit-button">応募する</a>
          <%end%>
        </div>
    <a href="/search"><<戻る</a>
</div>

app/views/pages/home.html.erb
<body>
    <header>
        <div class="top-img1">
            <div class="container text">
                <h1>働き手と雇用主を結ぶ<br>マッチング型<br>スキマバイト</h1>
                <div class="top-text">
                    <div class="info-buttons">
                        <a class="btn btn-primary" href ="/users/sign_in">ログインはこちら</a>
                        <a class="btn btn-warning sign_up_button" href ="/users/sign_up">新規登録はこちら</a>
                    </div>
                </div>
            </div>
        </div>
    </header>
</body>

app/views/pages/search.html.erb
<body>
    <div class="top-search container">
        <div class="search">
            <h2 class="search-title">検索結果一覧</h2>
            <div class="card search-card">
                <div class="card-body">
                <%= search_form_for @q, url: pages_search_path do |f| %>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                              <th class="text-nowrap"><%=label_tag "offers-title", "キーワード"%></th>
                              <td><%=f.search_field :title_or_contents_or_cautions_or_address_or_access_or_conditions_cont, id:"offers-title", placeholder: "例）セブンイレブン、渋谷、新宿", class:"form-control col-lg-5"%></td>
                            </tr>
                        </thead>
                        <thead>
                            <tr>
                              <th><%=label_tag "offers-category", "職種"%></th>
                              <td><%=f.collection_select :category_id_eq, @categories, :id, :name, {include_blank: "指定なし"}, {class: "form-control col-lg-3 col-md-4"}%></td>
                            </tr>
                        </thead>
                        <thead>
                            <tr>
                              <th><%=label_tag "offers-date", "出勤日"%></th>
                              <td><%=f.date_field :date_eq, id:"offers-date", class:"form-control col-lg-3 col-md-4"%></td>
                            </tr>
                        </thead>
                        <thead>
                            <tr>
                              <th><%=label_tag "walfare", "待遇" %></th>
                              <td>
                                <%=f.collection_check_boxes :offer_walfares_walfare_id_in, @walfares, :id, :name, include_hidden: false do |b|%>
                                    <%= b.check_box%>
                                    <%= b.label%>
                                <%end%>
                              </td>
                            </tr>
                            <tr>
                              <th><%=label_tag "offer-payment", "報酬"%></th>
                              <td>
                                <%= f.radio_button 'payment_gteq', '',{:checked => true}%>
                                 指定なし
                                <%= f.radio_button 'payment_gteq', '3000'%>
                                 ¥3,000~
                                <%= f.radio_button 'payment_gteq', '5000'%>
                                 ¥5,000~
                                <%= f.radio_button 'payment_gteq', '8000'%>
                                 ¥8,000~
                                <%= f.radio_button 'payment_gteq', '10000'%>
                                 ¥10,000~
                              </td>
                            </tr>
                        </thead>
                    </table>
                    <div class="search-button">
                        <%=submit_tag "検索する", class:"btn btn-primary"%>
                    </div>
                <%end%>
                </div>
            </div>
        </div>
        <div class="result">
            <div class="row">
                <%if @offer.present?%>
                    <% @offers.each do |offer| %>
                        <div class="col-lg-4 col-md-6 col-sd-12">
                            <div class="card offer-card">
                                <p><%= image_tag offer.images.to_s, class: "offer-img card-img-top" %></p>
                                <div class="card-body">
                                    <h6 class="card-title"><%= offer.title%></h6>
                                    <p class="card-text"><%= offer.date.strftime("%Y年%m月%d日")%><br><%= offer.start_time%>〜<%= offer.end_time%></p>
                                    <a class="btn btn-info information" href ="/detail/<%=offer.id%>">詳細</a>
                                    <h5 class="payment">¥<%=offer.payment.to_s(:delimited)%></h5>
                    　　          </div>
                            </div>
                        </div>
                    <%end%>
                <%else%>
                <div class="container">
                    <h5 class="text-caution">検索結果がありませんでした</h5>
                </div>
                <%end%>
            </div>
        </div>
        <div class="pagenation"><%= paginate @offers %></div>
    </div>
</body>